### ISSUE TITLE
Unknown pragma mark.

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#10]
I am getting this warning when building:
```
[ 66%] Building C object CMakeFiles/FreeRTOS_Emulator.dir/lib/Gfx/TUM_Draw.c.o
/tmp/project/lib/Gfx/TUM_Draw.c:586:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark - public
 ^
```

Is this line really required @alxhoff?

**Comment by alxhoff** [comment]
Ahhh yep, was from some experimenting once upon a time.

**Comment by PhilippvK** [comment]
Why am I getting a warning about this statement?

**Comment by alxhoff** [comment]
they're specific to XCode. I was playing around once upon a time with trying to mark the "public" methods more clearly and that was one of the things I tried out. GCC complains about them.
