### ISSUE TITLE
Implement a proper way of Task-safe Debug messages

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#21]
Printing via printf in parallel from multiple task can lead to problems such aus crashes.

I think it would be more optimal to have a single task which prints out messages send to a queue by other tasks inspired by the implementation in:

https://github.com/coon42/FreeRTOS-Posix-Simulator/blob/master/FreeRTOS_Posix/main.c

**Comment by PhilippvK** [comment]
I would only do this for verbose (debug) statements. Error handling should be fine with printf, in my opinion.

**Comment by alxhoff** [comment]
Agreed. Thread safety is a bit of a mess at the moment I think.

**Comment by PhilippvK** [comment]
I won't tackle it before the weekend. Toolchain is more important at the moment. If you want to implement it before, let me know.

**Comment by alxhoff** [comment]
I think i'll need to start recording the lectures :/

(edited by @PhilippvK, deleted email-related text)

**Comment by PhilippvK** [comment]
Oh no.. Are you using OBS for the screencast?

**Comment by alxhoff** [comment]
No idea what i'm going to use yet. I'll check OBS out though.

**Comment by PhilippvK** [comment]
Might be a bit overkill as it is used by professional streamers etc. but should also work on linux.

**Comment by alxhoff** [comment]
I think i will implement this over the weekend, introducing....TUM_error

**Comment by PhilippvK** [comment]
Are you going to have a main periodic print task collecting strings from other tasks via a queue if available?

**Comment by alxhoff** [comment]
yep, sounds like a good way to structure it. Although that would make it FreeRTOS dependent. I might just use an unwrapped pthread but yer same underlying idea I think.
