### ISSUE TITLE
Spamming state change can cause ball to leave area

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#24]
Totally unrelated to the Emulator itself but the ball can leave it's little box after changing screen.

**Comment by PhilippvK** [comment]
Isn’t the ball leaving the cage, too, if you wait until it accelerates fast enough to skip the border.

**Comment by alxhoff** [comment]
Yer it can do that. it's because of the super basic collision detection. Putting this issue here just in case one of us is bored sometime and wanting to delve into the depths of game engine algorithms :P

**Comment by alxhoff** [comment]
I feel like this I am never going to want to do this :P might also give away a bit too much of how to program games :P
