### ISSUE TITLE
Lint/Format Everything

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#26]
I recently saw, that the formatting (f. e. in TUM_Events.c) is a bit broken. Also I also need a few attempts to get it 100% correct.

We should probably add a linter to the travis checks to recognize them early enough.

**Comment by alxhoff** [comment]
Agreed. Ill add some more tests.

**Comment by alxhoff** [comment]
started work on [ci](https://github.com/alxhoff/FreeRTOS-Emulator/tree/ci) branch

**Comment by alxhoff** [comment]
Just needing proper coverage integration and it should be good
