### ISSUE TITLE
Add support for VSCode project generation

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#28]
I have most things done but testing everything on MacOS/Linux/Windows will take some days.

Documentation is covered in #7

**Comment by alxhoff** [comment]
Awesome. I'd focus on Linux though. Don't waste time on Windows 😋

**Comment by alxhoff** [comment]
Not sure what needs doing here. Something like [this](https://medium.com/@sam.romano18/visual-studio-code-setup-for-beginners-using-c-and-cmake-e92ab4f1fba1)?

**Comment by PhilippvK** [comment]
I am on it. I hope I have a pull request ready until tomorrow...

**Comment by alxhoff** [comment]
awesome. thanks
