### ISSUE TITLE
Finish Toolchains

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#29]
Cover:
- [x] Native Ubuntu 
- [x] Ubuntu VM 
- [x] Docker Container
- [x] Release Images (VM)
- [x] Documentation

@alxhoff Where can I upload the large ZIP archive with the VirtualBox Disk for the students? Gigamove Uploads do expire after a few days or am I wrong?

**Comment by alxhoff** [comment]
Yep. I would say you should upload it the Friday before semester starts at I'll send an email or that it'll be being used during the semester and that students need to download it

**Comment by alxhoff** [comment]
I would say this is done? documentation is a sure thing i'd say.
