### ISSUE TITLE
Update Pong Game branch to latest changes

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#30]
I would wait with this until we are done with the libraries and so on...

We could also improve a few parts of the game, like f. e. randomness.

**Comment by alxhoff** [comment]
Ah yep. I updated this a few times before. Ideally we pull the game (the tasks) out into separate sources so that updating the main.c is more straight forward.

**Comment by PhilippvK** [comment]
But wouldn’t this make the students life to easy organizing the project files in a meaningful way?

**Comment by alxhoff** [comment]
Yer I would break it up for sure
