### ISSUE TITLE
Code tidying

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#32]
After adding clang tidy for #26 it has found a lot of problems. Could be that the test just needs to be tweaked but there are things that need fixing.

Tidy has been added as a cmake target
```
cmake -DENABLE_CLANG_TIDY=ON ..
make tidy
```
or to export the tidies to file 
``` make tidy_list ```

**Comment by PhilippvK** [comment]
Hey, I just wanted to mention that I really appreciate your work on the CI integration and tidying. It seems like pretty complex stuff to me, but it’s a great feature!

**Comment by alxhoff** [comment]
yer no worries. this sort of stuff is a "do it once, reuse it for every future project" sort of thing :P. Still a few bugs in the tests and a heap of tidying to do.
