### ISSUE TITLE
Crashes when run from root directory

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#34]
> [ERROR] [SDL Error] Couldn't open /home/alxhoff/git/GitHub/resources
> "Failed to load image"    @-> /home/alxhoff/git/GitHub/FreeRTOS-Emulator/lib/Gfx/TUM_Draw.c:339, loadImage

**Comment by alxhoff** [comment]
Hardcoded image paths, need to decide if this should be how it should be or if we provide some other method.

**Comment by PhilippvK** [comment]
This sucks, way to much struggles for such a “simple” feature.

**Comment by alxhoff** [comment]
yer i don't think i'd be bothered but just mention somewhere that relative paths mean that you need to be careful where you run it from. Or could pass the resources folder in as a cmake where it could be resolved into an absolute path and passed to make as a define.....maybe i'll be motivated to do that at some point.
