### ISSUE TITLE
Add compile_commands.json to .gitignore?

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#4]
I saw, that you commented the corresponding line out in the `.gitignore` file. Could you explain what your intention was?

Also should there be an empty `build/` directory or should it be up to the user to create it?

**Comment by alxhoff** [comment]
Fixed. In the root dir is a symlink that places the created compile commands there for YouCompleteMe (i'd like this as Vim without this sucks). Have added a gitkeep to the build but removed the compile commands from build. Thanks for noticing!
