### ISSUE TITLE
[BUG] Demo comms has a strange char appended to output string

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#40]
**Describe the bug**
see title

**To Reproduce**
run demo

**Expected behavior**
only receive string "TCP test"

**Comment by PhilippvK** [comment]
How do you generate the tcp msg?

**Comment by alxhoff** [comment]
I think it's a static string. I imagine it's a `strcpy` somewhere with a +1 length or something so it's collecting some garbage before the terminator.

**Comment by PhilippvK** [comment]
Why is this still open?

**Comment by alxhoff** [comment]
turned up again :P, #43 didn't do it. I'll have a proper look some time.
