### ISSUE TITLE
[FEATURE] Error Handling for blocked Semaphores

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#45]
**Is your feature request related to a problem? Please describe.**
When an access to an already taken binary semaphore fails, the execution just continues, as no timeout was specified.
Statements like this can be found multiple times in the source code:
```
xSemaphoreTake(mouse.lock, 0);
```

**Describe the solution you'd like**
Either set the delay to f. e. `portMAX_DELAY` or skip the access to shared resources if the claim failed.

**Additional context**
See FreeRTOS Documentation: https://www.freertos.org/a00122.html

**Comment by alxhoff** [comment]
oh man I hope I didn't put in rookie mistakes like that :(

**Comment by alxhoff** [comment]
wow. Not sure how they ended up in there.....fixed
