### ISSUE TITLE
[FEATURE] Add more Colors to TUM_Draw

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#49]
**Is your feature request related to a problem? Please describe.**
No issues.

**Describe the solution you'd like**
Something like `MAGENTA`, `CYAN`,...

**Describe alternatives you've considered**
Students can define the Colors they need on their own.

**Additional context**
/

**Comment by alxhoff** [comment]
I will take inspiration from [here](https://github.com/alxhoff/uGFX-Fork/blob/master/src/gdisp/gdisp_colors.h)

**Comment by alxhoff** [comment]
TUMBlue is hands down the best color :P
