### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#5]
Hangs randomly, maybe unrelated but moving the mouse out and back into graphics window seems to cause the error.

Backtrace is a little confusing as to why it hangs

>Thread 11 (Thread 0x7fffecd50700 (LWP 13164)):
> 0  0x00007ffff7e08c45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
> 1  0x00007ffff68b683b in ?? () from /usr/lib/libxcb.so.1
> 2  0x00007ffff68b83bb in xcb_wait_for_special_event () from /usr/lib/libxcb.so.1
> 3  0x00007ffff607d931 in glPrimitiveBoundingBox () from /usr/lib/libGLX_mesa.so.0
> 4  0x00007ffff607da98 in glPrimitiveBoundingBox () from /usr/lib/libGLX_mesa.so.0
> 5  0x00007ffff607ecce in glPrimitiveBoundingBox () from /usr/lib/libGLX_mesa.so.0
> 6  0x00007ffff607fc3c in glPrimitiveBoundingBox () from /usr/lib/libGLX_mesa.so.0
> 7  0x00007ffff51aceba in ?? () from /usr/lib/dri/i965_dri.so
> 8  0x00007ffff51ad665 in ?? () from /usr/lib/dri/i965_dri.so
> 9  0x00007ffff51a90e5 in ?? () from /usr/lib/dri/i965_dri.so
> 10 0x00007ffff7e6810a in ?? () from /usr/lib/libSDL2-2.0.so.0
> 11 0x00007ffff7e5bf21 in ?? () from /usr/lib/libSDL2-2.0.so.0
> 12 0x00007ffff7e61298 in ?? () from /usr/lib/libSDL2-2.0.so.0
> 13 0x000055555555f566 in vDrawText (string=0x7fffa403dbb0 "[Q]uit, [C]hang[e] State", x=472, y=7, colour=0) at /home/alxhoff/git/GitHub/FreeRTOS-Emulator/lib/Gfx/TUM_Draw.c:432
> 14 0x000055555555fa90 in vHandleDrawJob (job=0x7fffa403eba0) at /home/alxhoff/git/GitHub/FreeRTOS-Emulator/lib/Gfx/TUM_Draw.c:509
> 15 0x000055555555fe55 in vDrawUpdateScreen () at /home/alxhoff/git/GitHub/FreeRTOS-Emulator/lib/Gfx/TUM_Draw.c:597
> 16 0x0000555555557a9f in vSwapBuffers (pvParameters=0x0) at /home/alxhoff/git/GitHub/FreeRTOS-Emulator/src/main.c:183
> 17 0x0000555555559b60 in prvWaitForStart (pvParams=0x5555572611e0) at /home/alxhoff/git/GitHub/FreeRTOS-Emulator/lib/FreeRTOS_Kernel/portable/GCC/Posix/port.c:496
> 18 0x00007ffff7e024cf in start_thread () from /usr/lib/libpthread.so.0
> 19 0x00007ffff797d2d3 in clone () from /usr/lib/libc.so.6

Similar issue [here](https://forum.manjaro.org/t/strange-freezing-of-individual-windows/117722)

@PhilippvK do you get this issue or is it to do with my distro? I am running manjaro.

**Comment by PhilippvK** [comment]
No error messages or crashes?

**Comment by PhilippvK** [comment]
I would recommend to wait until I have my changes in TUM_Draw and TUM_Events online. Maybe it will change the issue.

**Comment by alxhoff** [comment]
No errors sadly, all TCP comms etc keep going, it doesn't crash but just enters a deadlock for the graphic stuff. So I imagine it's some poorly implemented demo code from me :P

**Comment by alxhoff** [comment]
Also please give me baby size PRs :P

**Comment by PhilippvK** [comment]
I will do my best. Sorry for the delays.

**Comment by alxhoff** [comment]
Tried this on another arch machine and got similar issues. Both the other machine and mine are running i3 window manager. What is your machine running in terms of distro and graphical interface/window manager?

**Comment by alxhoff** [comment]
Just to double check. @PhilippvK  on your system if you mouse in and out of the window ~10+ times it doesn't hang?

**Comment by PhilippvK** [comment]
Cannot reproduce on native ubuntu. Running very very smooth, as the computer is quiet fast and has a decent gpu.

Reproducing inside vms on my mac is tricky as the performance is bad anyway so i cannot tell if such behavior is related to the problem you mentioned.

Gonna try it out inside VMs on Linux/Windows Hosts, soon.

**Comment by alxhoff** [comment]
Ok cool. I'm going to send it to my colleagues for them to test and see if anyone else gets it as they all have varying distros etc

**Comment by PhilippvK** [comment]
Latest 64 bit Manjaro inside virtualbox also works for me.

**Comment by alxhoff** [comment]
strange. I'll send it out to my colleagues and see if any of them have problems. What desktop environments run on your systems? I am using i3 window manager and that could be why

**Comment by PhilippvK** [comment]
On ubuntu: Gnome desktop

Inside Manjaro VM: XFCE

Definitely could be related to i3.

**Comment by alxhoff** [comment]
i'd say so as on my housemates machine it also didn't work and he runs i3 ontop of pure arch

**Comment by PhilippvK** [comment]
Try it again after mergin the opengl context stuff. However odds are low...

**Comment by alxhoff** [comment]
fingers crossed

**Comment by alxhoff** [comment]
Also confirmed fixed on secondary Arch/i3 setup
