### ISSUE TITLE
[FEATURE] Document how ASTYLE binary has to be installed

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#51]
**Is your feature request related to a problem? Please describe.**
When running `make format` even if I installed the `astyle` package installed, it the make target tries to find `bin/astyle` which is not available (on Ubuntu).

**Describe the solution you'd like**
remove the `bin` prefix? Why is it required? Also the package dependency is currently not mentioned in the readme and wiki.

**Describe alternatives you've considered**
-

**Additional context**
My workaround was to break a `bin` directory with a symlink to the astyle executable inside.

**Comment by PhilippvK** [comment]
A different error occurs now:

```
Scanning dependencies of target astyle
[ 69%] Creating directories for 'astyle'
[ 73%] Performing download step (git clone) for 'astyle'
Cloning into 'origin'...
CMake Error at tmp/astyle-gitclone.cmake:49 (message):
  Failed to checkout tag: 'v1.2'


CMakeFiles/astyle.dir/build.make:89: recipe for target 'external/astyle/stamp/astyle-download' failed
make[2]: *** [external/astyle/stamp/astyle-download] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/astyle.dir/all' failed
make[1]: *** [CMakeFiles/astyle.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by alxhoff** [comment]
did you run `make` before `make format`? The first call to make should compile the binary

**Comment by PhilippvK** [comment]
Not sure. Have to double check

**Comment by alxhoff** [comment]
I made this mistake once and it could be the problem

**Comment by PhilippvK** [comment]
Hmm what are your versions of cmake and git?

**Comment by PhilippvK** [comment]
It is related to `cmake 3.5` which seems to be the default in Lubuntu 16.04... 

Any other idea than recommending to install it via:
```
VERSION=3.16 &&\
  BUILD=5 &&\
  wget -q https://cmake.org/files/v$VERSION/cmake-$VERSION.$BUILD-Linux-x86_64.sh &&\
  mkdir /opt/cmake &&\
  sh cmake-$VERSION.$BUILD-Linux-x86_64.sh --prefix=/opt/cmake --skip-license --exclude-subdir &&\
  ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake &&\
  rm cmake-$VERSION.$BUILD-Linux-x86_64.sh
```
?

**Comment by alxhoff** [comment]
Silly ubuntu. I have cmake 3.17. Urm, not sure if the students will really use it. Maybe drop a note in the wiki about how to install a compatible cmake version if they are so inclined to use the target?
