### ISSUE TITLE
[FEATURE] Custom Fonts

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#56]
**Is your feature request related to a problem? Please describe.**
You can not change the Font easily or use multiple fonts in one program.

**Describe the solution you'd like**
_Best Option:_ Implement a way to change fonts on the fly.

**Describe alternatives you've considered**
At least allow overwriting the default font (by using `#ifndef DEFAULT_FONT ...` in `TUM_Draw.h`.

**Comment by alxhoff** [comment]
good idea

**Comment by PhilippvK** [comment]
Similar situation exists for the Waveforms. At the moment they only can be defined in the libraries itself or am I wrong?

**Comment by alxhoff** [comment]
yer i think so. i'll look into a solution. Maybe some sort of auxiliary init function that takes in a custom font/audio

**Comment by PhilippvK** [comment]
Hm, I would prefer to be able to use more than one font (and font size) during program execution. Do not feel forced to implement it, if its to complex. Its just a nice to have thing.

**Comment by alxhoff** [comment]
i'll make a font API now
