### ISSUE TITLE
[IMPROVEMENT] Fix doxygen mess

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#58]

**Comment by PhilippvK** [comment]
Also i think that not every function/variable prefix is FreeRTOS-conform (p, v, px,...)

Maybe you can double check this when cleaning the other "mess".

**Comment by alxhoff** [comment]
yer there is so much to do in terms of documentation. I should make this issue a bit more general

**Comment by PhilippvK** [comment]
@alxhoff Hey, in the doxygen for the font api stuff, you have written `Retrieved` instead of `Retrieves` at least two times. Also I think the `gh-pages` output does not list a TUM_Font module yet,

**Comment by alxhoff** [comment]
Yep this is both correct, didn't add a Fonts modules in my haste. Will see if I can get around to putting a few hours into this tomorrow.
