### ISSUE TITLE
Parsing of Bin Folder Path fails when using gdbserver

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#6]
One of my solutions to connect VSCode with the VM makes use of a gdb server. The execution using it is failing right in the main function: 

```
Failed to match 'FreeRTOS_Emulator' with '(.*)/', returning 1
n_
```

It seems like you only accept `argv[0]` to habe at least one forward slash `/` like common with `./FreeRTOS_Emulator` and `../bin/FreeRTOS_Emulator`, but in my case it is simply `FreeRTOS_Emulator`. Thus the REGEX is not satisfied.

The fix in `getBinFolderPath` should be trivial, but I would appreciate if you would take care of it.

**Comment by alxhoff** [comment]
I shall do it tonight as I sip on my beer

**Comment by PhilippvK** [comment]
Many thanks. No hurries.

**Comment by PhilippvK** [comment]
Works flawlessly.

**Comment by PhilippvK** [comment]
Unfortunately I found another bug with the new implementation.

If you have
`#define LOGO_FILENAME "../resources/freertos.jpg"`

and run the executable inside the bin directory, the bin_path would be `.` making the concatenated path of the Image `.../resources/freertos.jpg`. 

I think there is a `/` missing.

@alxhoff

**Comment by alxhoff** [comment]
ok. I will fix this up. There are a few gross problems like this floating about as I went for quick and dirty at the time.
