### ISSUE TITLE
[IMPROVEMENT] Cache images between frames

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#61]
**What should be improved?**
Drawing larger images or many small ones reduces the framerate heavily, even when running on native Linux. Caching the files could be worth checking out.

**Describe the solution you'd like**
Do not destroy the texture/surface between every frame as this should hopefully reduce the overall load.

**Additional context**
Maybe make this optional. For uGFX there is a method which enables the caching on a per-image basis.

This could also reduce the performance impact of scaling images if the scaled version of the texture is caches instead of the original, but them you would need to check if the scale factor has changed...

**Comment by alxhoff** [comment]
Do you remember if calling `SDL_CreateRenderer` when binding GL context was necessary? Or is the important call `SDL_GL_MakeCurrent`?

**Comment by PhilippvK** [comment]
I am very sure, that the renderer has to be created after claiming the context which needs to be done in the thread performing the drawing operations...

Why are you asking?

**Comment by alxhoff** [comment]
Problem is that loaded images textures are tied to a renderer and if the renderer is being potentially recreated then the image textures become invalid (i think).

**Comment by PhilippvK** [comment]
You can try out moving it, but you probably would also try to move the context claiming which likely breaks the drawing stuff again..

**Comment by alxhoff** [comment]
the context claiming only needs the window and doesn't actually reference the renderer which is why I was wondering if they are actually connected.

**Comment by PhilippvK** [comment]
I know it is not a good habit to do such things, but if we assume, that a context will only be created one, it should be fine?

**Comment by alxhoff** [comment]
yer I don't really want to make this assumption but I can't find documentation that links the context and the renderer

**Comment by PhilippvK** [comment]
Alternatively, you could let the user init all the used images in main, so the caching could be done in vBindDrawing each time after the renderer was created.

**Comment by alxhoff** [comment]
yes but this would require keeping a list of all loaded images etc which would be cumbersome

**Comment by PhilippvK** [comment]
I think creating the renderer without a context resulted an SDL error or null pointer.

**Comment by PhilippvK** [comment]
Try it out..

**Comment by PhilippvK** [comment]
I also think the complexity of this is high, given the fact that we do not know if it improves the performance or if it is going to introduce other issues.

**Comment by PhilippvK** [comment]
I am very impressed. Improvements are definitely recognizable (f.e. when Drawing the Logo >10 times).

In my VM I sometimes experience crashed when the Emulator is launching. If have the feeling that that it gets worse the more graphics are initialized in the `main()` but I would ignore it for now. Happened for the 4th time in 2 week now.
