### ISSUE TITLE
VS code integration documentation in README

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#7]
@PhilippvK Just thought i'd leave a reminder here that we should document the usage of VS code in the README.

**Comment by PhilippvK** [comment]
I was going to provide a whole set of manual pages in this Repos Wiki.

**Comment by PhilippvK** [comment]
I havent looked into the tracing stuff you implemented yet. Could you possibly write a short manual on how to use it in the following weeks.

Also do you see any way integrating the tracing results into the IDE?

**Comment by alxhoff** [comment]
Ahhh right, forgot about that. I implemented that ages ago to help me debug some issue. Hopefully my bash history still has teh right commands :P, will document it

**Comment by alxhoff** [comment]
> I was going to provide a whole set of manual pages in this Repos Wiki.

Sound good. I'd just add a link from the readme or just add a note that there are wiki pages. So students don't miss it

**Comment by PhilippvK** [comment]
When I do the wiki, I probably also move the YCM (vim) related part of the readme there. And yes i will link it.

**Comment by alxhoff** [comment]
Sounds like a good idea

**Comment by PhilippvK** [comment]
I also have a tool to make a HTML/PDF export of the Wiki.

**Comment by alxhoff** [comment]
a pdf export would be useful for students I think
