### ISSUE TITLE
[FEATURE] Support moving the contents of a frame by a delta-offset

### ISSUE THREAD

**Issue by PhilippvK** [alxhoff/FreeRTOS-Emulator#70]
**Is your feature request related to a problem? Please describe.**
Students often struggle making the contents of the screen move using the mouse coordinates. It is very annoying to add deltaX and deltaY values to every call of tumDraw functions.

**Describe the solution you'd like**
Because auf the way how the drawing request are collected and actually drawn it should not be to hard to add a global offset for the current frame which can set using a function call.

**Describe alternatives you've considered**
Do not change anything to keep the exercises challenging enough.

**Additional context**
This is not very relevant and only of interest if the Emulator will be used in the winter term as well.

**Comment by alxhoff** [comment]
hmmmm interesting.
