### ISSUE TITLE
[FEATURE] Emulator config

### ISSUE THREAD

**Issue by alxhoff** [alxhoff/FreeRTOS-Emulator#74]
**Is your feature request related to a problem? Please describe.**
Changing "variables" such as SCREEN_HEIGHT and possible enabling of features such as FPS limit could be set in a FreeRTOSConfig style file.

**Describe the solution you'd like**
A `EmulatorConfig.h` that allows for user build control

@PhilippvK please help me in listing possible config options that would be useful

So far I have:

- Screen sizes 
- Window title
- Default font
- fonts directory
- resources directory
- enabling fps limit

**Comment by PhilippvK** [comment]
Except 
- Specify Target framerate

I do not really have other ideas...

**Comment by alxhoff** [comment]
thanks. I am sure people will mention things in the future
